name: steamkeys_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - matplotlib
  - seaborn
  - pyspark
  - pymongo
  - kafka-python
  - pip:
      - confluent-kafka
      - selenium==4.10.0
      - undetected-chromedriver
      - webdriver-manager
      - requests
      - fake-useragent
      - beautifulsoup4
      - lxml